export const viewProduct: string;
export const productArea: string;
export const productDetailsSection: string;
export const productName: string;
export const productPrice: string;
export const stock: string;
export const aboutSection: string;
export const hr: string;
export const actionButtons: string;
