export const viewProduct: string;
export const productArea: string;
export const productImagesSection: string;
export const productImageActive: string;
export const productDetailsSection: string;
export const productName: string;
export const productPrice: string;
export const productImagesOptions: string;
export const productImagesItem: string;
